Added php pre-install script

diff --git a/src/lib/pre-install b/src/lib/pre-install
--- a/src/lib/pre-install
+++ b/src/lib/pre-install
@@ -2,21 +2,23 @@
 
 pushd `dirname $0` > /dev/null 2>&1;
 
-configFile='../conf/config.ini';
-httpdFile='../conf/httpd.conf';
 
-if [ ! -f $configFile ]; then
-	# TODO :: Prompt for installation configuration stuff
-	cp ${configFile}.orig $configFile;
+# find path to php
+PHP_BIN=`which php`
+if [ -z "$PHP_BIN" ]; then
+	echo 'PHP executable not found, enter path: '
+	read PHP_BIN
 fi
 
-source $configFile;
 
-cat << EOF > $httpdFile
-Alias $MOUNT_PATH $MOUNT_DIR
+# run pre-install.php
+if [ -x "$PHP_BIN" ]; then
+	$PHP_BIN ./pre-install.php
+else
+	echo 'PHP executable not found, unable to run pre-install.php'
+	exit 1;
+fi
 
-EOF
 
 popd > /dev/null 2>&1;
-
 exit 0;
